### PR TITLE
Tweaked const declaration style

### PR DESCRIPTION
**Pull request by jvermillard**
More in the style of https://golang.org/doc/effective_go.html#constants
And more consistant accross the file

### CODE REVIEW

**Comment by dustin** [comment]
This change doesn't apply.

I think I'd prefer you tried to avoid really long lines.  The comments at the end of fairly long lines could be placed above.

**Comment by jvermillard** [comment]
Fine.
Will you merge it if I move the comments back to top line?

**Comment by dustin** [comment]
I'd prefer that.  The patch doesn't apply currently, though.

**Comment by jvermillard** [comment]
OK fixed long line comments.

merge with current master, but maybe it's not for you because you didn't pushed #17 patch to master ? (an unrelated line was modified by go fmt)

**Comment by dustin** [comment]
Yeah, I did fail to push.  Sorry about that.  I've fixed this up and pushed it.

**Pull request closed without merging**
